//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System.ServiceModel;
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl", ConfigurationName="FormSessionPortType")]
public interface FormSessionPortType
{

    //[OperationContract (Action = "getVersion")]
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.hiso.govt.nz/10014.2/1.0/formsession) of message getVersionRequest does not match the default value (http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl)

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getVersion" +
        "", ReplyAction = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getVersionResponse")]
    
    //[System.ServiceModel.OperationContractAttribute(Action = "getVersion", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionRequest))]
    getVersionResponse getVersion(getVersionRequest request);
    
    //[System.ServiceModel.OperationContractAttribute(Action="getVersion", ReplyAction="*")]
    //System.Threading.Tasks.Task<getVersionResponse1> getVersionAsync(getVersionRequest1 request);
    //[OperationContract]
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.hiso.govt.nz/10014.2/1.0/formsession) of message getDeliveryOptionsRequest does not match the default value (http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl)
    //[System.ServiceModel.OperationContractAttribute(Action = "getDeliveryOptions", ReplyAction = "*")]
    [System.ServiceModel.OperationContractAttribute(Action = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getDeliveryOptions" +
        "", ReplyAction = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getDeliveryOptionsResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionRequest))]
    getDeliveryOptionsResponse getDeliveryOptions(getDeliveryOptionsRequest request);
    
    //[System.ServiceModel.OperationContractAttribute(Action="getDeliveryOptions", ReplyAction="*")]
    //System.Threading.Tasks.Task<getDeliveryOptionsResponse1> getDeliveryOptionsAsync(getDeliveryOptionsRequest1 request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.hiso.govt.nz/10014.2/1.0/formsession) of message getDataRequest does not match the default value (http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl)
    //[System.ServiceModel.OperationContractAttribute(Action = "getData", ReplyAction = "*")]
     [System.ServiceModel.OperationContractAttribute(Action = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getData" +
        "", ReplyAction = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionRequest))]
    //[System.ServiceModel.MessageContractAttribute(WrapperNamespace = "http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped = true)]
    getDataResponse getData(getDataRequest request);
    
    //[System.ServiceModel.OperationContractAttribute(Action="getData", ReplyAction="*")]
    //System.Threading.Tasks.Task<getDataResponse1> getDataAsync(getDataRequest1 request);
   
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.hiso.govt.nz/10014.2/1.0/formsession) of message saveContainerRequest does not match the default value (http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl)
     //[System.ServiceModel.OperationContractAttribute(Action = "saveContainer", ReplyAction = "*")]
    [System.ServiceModel.OperationContractAttribute(Action = "http://www.hiso.govt.nz/10014.2/1.0/formsession/saveContainer" +
        "", ReplyAction = "http://www.hiso.govt.nz/10014.2/1.0/formsession/saveContainerResponse")] 
    [System.ServiceModel.XmlSerializerFormatAttribute()]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionResponse))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionRequest))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewResponse))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewRequest))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerResponse))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerRequest))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataResponse))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataRequest))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsResponse))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsRequest))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionResponse))]
     [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionRequest))]
    saveContainerResponse saveContainer(saveContainerRequest request);
    
    //[System.ServiceModel.OperationContractAttribute(Action="saveContainer", ReplyAction="*")]
    //System.Threading.Tasks.Task<saveContainerResponse1> saveContainerAsync(saveContainerRequest1 request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.hiso.govt.nz/10014.2/1.0/formsession) of message getFormViewRequest does not match the default value (http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl)
    //[System.ServiceModel.OperationContractAttribute(Action = "getFormView", ReplyAction = "*")]

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getFormView" +
        "", ReplyAction = "http://www.hiso.govt.nz/10014.2/1.0/formsession/getFormViewResponse")] 
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionRequest))]
    getFormViewResponse getFormView(getFormViewRequest request);
    
    //[System.ServiceModel.OperationContractAttribute(Action="getFormView", ReplyAction="*")]
    //System.Threading.Tasks.Task<getFormViewResponse1> getFormViewAsync(getFormViewRequest1 request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.hiso.govt.nz/10014.2/1.0/formsession) of message processActionRequest does not match the default value (http://www.hiso.govt.nz/10014.2/1.0/formsession/wsdl)
    //[System.ServiceModel.OperationContractAttribute(Action = "processAction", ReplyAction = "*")]
    [System.ServiceModel.OperationContractAttribute(Action = "http://www.hiso.govt.nz/10014.2/1.0/formsession/processAction" +
        "", ReplyAction = "http://www.hiso.govt.nz/10014.2/1.0/formsession/processActionResponse")] 
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessActionRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetFormViewRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SaveContainerRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDataRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetDeliveryOptionsRequest))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GetVersionRequest))]
    processActionResponse processAction(processActionRequest request);
    
    //[System.ServiceModel.OperationContractAttribute(Action="processAction", ReplyAction="*")]
    //System.Threading.Tasks.Task<processActionResponse1> processActionAsync(processActionRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetVersionResponseReturn
{
    
    private string applicationField;
    
    private string applicationVersionField;
    
    private decimal hisoversionField;
    
    private decimal dictionaryVersionField;
    
    private bool dictionaryVersionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
    public string application
    {
        get
        {
            return this.applicationField;
        }
        set
        {
            this.applicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
    public string applicationVersion
    {
        get
        {
            return this.applicationVersionField;
        }
        set
        {
            this.applicationVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public decimal hisoversion
    {
        get
        {
            return this.hisoversionField;
        }
        set
        {
            this.hisoversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public decimal dictionaryVersion
    {
        get
        {
            return this.dictionaryVersionField;
        }
        set
        {
            this.dictionaryVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dictionaryVersionSpecified
    {
        get
        {
            return this.dictionaryVersionFieldSpecified;
        }
        set
        {
            this.dictionaryVersionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class ProcessActionResponse
{
    
    private ProcessActionResponseReturn returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ProcessActionResponseReturn @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class ProcessActionResponseReturn
{
    
    private bool processedField;
    
    private FormData dataContainerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool processed
    {
        get
        {
            return this.processedField;
        }
        set
        {
            this.processedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FormData dataContainer
    {
        get
        {
            return this.dataContainerField;
        }
        set
        {
            this.dataContainerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormData
{
    
    private FormMetaData formMetaDataField;
    
    private object submittedDataField;
    
    private FormDataResponseData responseDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FormMetaData formMetaData
    {
        get
        {
            return this.formMetaDataField;
        }
        set
        {
            this.formMetaDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public object submittedData
    {
        get
        {
            return this.submittedDataField;
        }
        set
        {
            this.submittedDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FormDataResponseData responseData
    {
        get
        {
            return this.responseDataField;
        }
        set
        {
            this.responseDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaData
{
    
    private FormMetaDataFormInstanceId formInstanceIdField;
    
    private FormMetaDataFormInstanceVersion formInstanceVersionField;
    
    private FormMetaDataFormEngineId formEngineIdField;
    
    private FormMetaDataFormInstanceCreationDate formInstanceCreationDateField;
    
    private FormMetaDataFormInstanceOperationMode formInstanceOperationModeField;
    
    private FormMetaDataFormInstanceDescription formInstanceDescriptionField;
    
    private FormMetaDataFormDefinitionId formDefinitionIdField;
    
    private FormMetaDataFormDefinitionVersion formDefinitionVersionField;
    
    private FormMetaDataFormDefinitionDescription formDefinitionDescriptionField;
    
    private FormMetaDataFormDefinitionTitle formDefinitionTitleField;
    
    private FormMetaDataEncryptedFlag encryptedFlagField;
    
    private FormMetaDataSignatures signaturesField;
    
    private FormMetaDataRecipientAccount recipientAccountField;
    
    private FormMetaDataCcRecipientAccount[] copyToRecipientAccountsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FormMetaDataFormInstanceId formInstanceId
    {
        get
        {
            return this.formInstanceIdField;
        }
        set
        {
            this.formInstanceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FormMetaDataFormInstanceVersion formInstanceVersion
    {
        get
        {
            return this.formInstanceVersionField;
        }
        set
        {
            this.formInstanceVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FormMetaDataFormEngineId formEngineId
    {
        get
        {
            return this.formEngineIdField;
        }
        set
        {
            this.formEngineIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public FormMetaDataFormInstanceCreationDate formInstanceCreationDate
    {
        get
        {
            return this.formInstanceCreationDateField;
        }
        set
        {
            this.formInstanceCreationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public FormMetaDataFormInstanceOperationMode formInstanceOperationMode
    {
        get
        {
            return this.formInstanceOperationModeField;
        }
        set
        {
            this.formInstanceOperationModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public FormMetaDataFormInstanceDescription formInstanceDescription
    {
        get
        {
            return this.formInstanceDescriptionField;
        }
        set
        {
            this.formInstanceDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public FormMetaDataFormDefinitionId formDefinitionId
    {
        get
        {
            return this.formDefinitionIdField;
        }
        set
        {
            this.formDefinitionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public FormMetaDataFormDefinitionVersion formDefinitionVersion
    {
        get
        {
            return this.formDefinitionVersionField;
        }
        set
        {
            this.formDefinitionVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public FormMetaDataFormDefinitionDescription formDefinitionDescription
    {
        get
        {
            return this.formDefinitionDescriptionField;
        }
        set
        {
            this.formDefinitionDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public FormMetaDataFormDefinitionTitle formDefinitionTitle
    {
        get
        {
            return this.formDefinitionTitleField;
        }
        set
        {
            this.formDefinitionTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public FormMetaDataEncryptedFlag encryptedFlag
    {
        get
        {
            return this.encryptedFlagField;
        }
        set
        {
            this.encryptedFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public FormMetaDataSignatures signatures
    {
        get
        {
            return this.signaturesField;
        }
        set
        {
            this.signaturesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public FormMetaDataRecipientAccount recipientAccount
    {
        get
        {
            return this.recipientAccountField;
        }
        set
        {
            this.recipientAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ccRecipientAccount", IsNullable=false)]
    public FormMetaDataCcRecipientAccount[] copyToRecipientAccounts
    {
        get
        {
            return this.copyToRecipientAccountsField;
        }
        set
        {
            this.copyToRecipientAccountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormInstanceId
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormInstanceVersion
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormEngineId
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormInstanceCreationDate
{
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
    public System.DateTime Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormInstanceOperationMode
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormInstanceDescription
{
    
    private string conceptIDField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
    public string conceptID
    {
        get
        {
            return this.conceptIDField;
        }
        set
        {
            this.conceptIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormDefinitionId
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormDefinitionVersion
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormDefinitionDescription
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataFormDefinitionTitle
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataEncryptedFlag
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataSignatures
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataRecipientAccount
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormMetaDataCcRecipientAccount
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formInstanceMeta")]
public partial class FormDataResponseData
{
    
    private string applicationResponseCodeField;
    
    private string applicationResponseMessageField;
    
    private string receivingSystemIdField;
    
    private string actionIdField;
    
    private object actionContainerField;
    
    private object dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string applicationResponseCode
    {
        get
        {
            return this.applicationResponseCodeField;
        }
        set
        {
            this.applicationResponseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string applicationResponseMessage
    {
        get
        {
            return this.applicationResponseMessageField;
        }
        set
        {
            this.applicationResponseMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string receivingSystemId
    {
        get
        {
            return this.receivingSystemIdField;
        }
        set
        {
            this.receivingSystemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string actionId
    {
        get
        {
            return this.actionIdField;
        }
        set
        {
            this.actionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public object actionContainer
    {
        get
        {
            return this.actionContainerField;
        }
        set
        {
            this.actionContainerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public object data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class ProcessActionRequest
{
    
    private string sessionKeyField;
    
    private string actionIdField;
    
    private System.Xml.XmlElement actionContainerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string sessionKey
    {
        get
        {
            return this.sessionKeyField;
        }
        set
        {
            this.sessionKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
    public string actionId
    {
        get
        {
            return this.actionIdField;
        }
        set
        {
            this.actionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.Xml.XmlElement actionContainer
    {
        get
        {
            return this.actionContainerField;
        }
        set
        {
            this.actionContainerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetFormViewResponse
{
    
    private GetFormViewResponseReturn returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public GetFormViewResponseReturn @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetFormViewResponseReturn
{
    
    private string resumePathField;
    
    private FormData dataContainerField;
    
    private string viewField;
    
    private string viewTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string resumePath
    {
        get
        {
            return this.resumePathField;
        }
        set
        {
            this.resumePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FormData dataContainer
    {
        get
        {
            return this.dataContainerField;
        }
        set
        {
            this.dataContainerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string view
    {
        get
        {
            return this.viewField;
        }
        set
        {
            this.viewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
    public string viewType
    {
        get
        {
            return this.viewTypeField;
        }
        set
        {
            this.viewTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetFormViewRequest
{
    
    private string sessionKeyField;
    
    private string formInstanceIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string sessionKey
    {
        get
        {
            return this.sessionKeyField;
        }
        set
        {
            this.sessionKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
    public string formInstanceId
    {
        get
        {
            return this.formInstanceIdField;
        }
        set
        {
            this.formInstanceIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class SaveContainerResponse
{
    
    private SaveContainerResponseReturn returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SaveContainerResponseReturn @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class SaveContainerResponseReturn
{
    
    private bool responseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool response
    {
        get
        {
            return this.responseField;
        }
        set
        {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class SaveContainerRequest
{
    
    private string sessionKeyField;
    
    private string resumePathField;
    
    private FormData dataContainerField;
    
    private string viewField;
    
    private string viewTypeField;
    
    private string viewSignatureField;
    
    private bool completedField;
    
    private bool continueSessionField;
    
    private bool continueSessionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string sessionKey
    {
        get
        {
            return this.sessionKeyField;
        }
        set
        {
            this.sessionKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string resumePath
    {
        get
        {
            return this.resumePathField;
        }
        set
        {
            this.resumePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FormData dataContainer
    {
        get
        {
            return this.dataContainerField;
        }
        set
        {
            this.dataContainerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string view
    {
        get
        {
            return this.viewField;
        }
        set
        {
            this.viewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
    public string viewType
    {
        get
        {
            return this.viewTypeField;
        }
        set
        {
            this.viewTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string viewSignature
    {
        get
        {
            return this.viewSignatureField;
        }
        set
        {
            this.viewSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public bool completed
    {
        get
        {
            return this.completedField;
        }
        set
        {
            this.completedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool continueSession
    {
        get
        {
            return this.continueSessionField;
        }
        set
        {
            this.continueSessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool continueSessionSpecified
    {
        get
        {
            return this.continueSessionFieldSpecified;
        }
        set
        {
            this.continueSessionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetDataResponse
{
    
    private GetDataResponseReturn returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public GetDataResponseReturn @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetDataResponseReturn
{
    
    private FormData dataContainerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FormData dataContainer
    {
        get
        {
            return this.dataContainerField;
        }
        set
        {
            this.dataContainerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetDataRequest
{
    
    private string sessionKeyField;
    
    private FormData dataContainerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string sessionKey
    {
        get
        {
            return this.sessionKeyField;
        }
        set
        {
            this.sessionKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public FormData dataContainer
    {
        get
        {
            return this.dataContainerField;
        }
        set
        {
            this.dataContainerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetDeliveryOptionsResponse
{
    
    private GetDeliveryOptionsResponseReturn returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public GetDeliveryOptionsResponseReturn @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetDeliveryOptionsResponseReturn
{
    
    private string uRLField;
    
    private string messageIDField;
    
    private string recipientAccountField;
    
    private string senderAccountField;
    
    private string senderPasswordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string URL
    {
        get
        {
            return this.uRLField;
        }
        set
        {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string messageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
    public string recipientAccount
    {
        get
        {
            return this.recipientAccountField;
        }
        set
        {
            this.recipientAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
    public string senderAccount
    {
        get
        {
            return this.senderAccountField;
        }
        set
        {
            this.senderAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string senderPassword
    {
        get
        {
            return this.senderPasswordField;
        }
        set
        {
            this.senderPasswordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetDeliveryOptionsRequest
{
    
    private string sessionKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string sessionKey
    {
        get
        {
            return this.sessionKeyField;
        }
        set
        {
            this.sessionKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetVersionResponse
{
    
    private GetVersionResponseReturn returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public GetVersionResponseReturn @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession")]
public partial class GetVersionRequest
{
    
    private string sessionKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string sessionKey
    {
        get
        {
            return this.sessionKeyField;
        }
        set
        {
            this.sessionKeyField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getVersionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sessionKey;
    
    public getVersionRequest()
    {
    }
    
    public getVersionRequest(string sessionKey)
    {
        this.sessionKey = sessionKey;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getVersionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    public GetVersionResponseReturn @return;
    
    public getVersionResponse()
    {
    }
    
    public getVersionResponse(GetVersionResponseReturn @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryOptions", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getDeliveryOptionsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sessionKey;
    
    public getDeliveryOptionsRequest()
    {
    }
    
    public getDeliveryOptionsRequest(string sessionKey)
    {
        this.sessionKey = sessionKey;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryOptionsResponse", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getDeliveryOptionsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    public GetDeliveryOptionsResponseReturn @return;
    
    public getDeliveryOptionsResponse()
    {
    }
    
    public getDeliveryOptionsResponse(GetDeliveryOptionsResponseReturn @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getData", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getDataRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sessionKey;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=1)]
    public FormData dataContainer;
    
    public getDataRequest()
    {
    }
    
    public getDataRequest(string sessionKey, FormData dataContainer)
    {
        this.sessionKey = sessionKey;
        this.dataContainer = dataContainer;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDataResponse", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    public GetDataResponseReturn @return;
    
    public getDataResponse()
    {
    }
    
    public getDataResponse(GetDataResponseReturn @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="saveContainer", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class saveContainerRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sessionKey;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string resumePath;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=2)]
    public FormData dataContainer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=3)]
    public string view;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=4)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string viewType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=5)]
    public string viewSignature;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=6)]
    public bool completed;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=7)]
    public bool continueSession;
    
    public saveContainerRequest()
    {
    }
    
    public saveContainerRequest(string sessionKey, string resumePath, FormData dataContainer, string view, string viewType, string viewSignature, bool completed, bool continueSession)
    {
        this.sessionKey = sessionKey;
        this.resumePath = resumePath;
        this.dataContainer = dataContainer;
        this.view = view;
        this.viewType = viewType;
        this.viewSignature = viewSignature;
        this.completed = completed;
        this.continueSession = continueSession;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="saveContainerResponse", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class saveContainerResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    public SaveContainerResponseReturn @return;
    
    public saveContainerResponse()
    {
    }
    
    public saveContainerResponse(SaveContainerResponseReturn @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFormView", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getFormViewRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sessionKey;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string formInstanceId;
    
    public getFormViewRequest()
    {
    }
    
    public getFormViewRequest(string sessionKey, string formInstanceId)
    {
        this.sessionKey = sessionKey;
        this.formInstanceId = formInstanceId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFormViewResponse", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class getFormViewResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    public GetFormViewResponseReturn @return;
    
    public getFormViewResponse()
    {
    }
    
    public getFormViewResponse(GetFormViewResponseReturn @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="processAction", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class processActionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string sessionKey;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string actionId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=2)]
    public System.Xml.XmlElement actionContainer;
    
    public processActionRequest()
    {
    }
    
    public processActionRequest(string sessionKey, string actionId, System.Xml.XmlElement actionContainer)
    {
        this.sessionKey = sessionKey;
        this.actionId = actionId;
        this.actionContainer = actionContainer;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="processActionResponse", WrapperNamespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", IsWrapped=true)]
public partial class processActionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hiso.govt.nz/10014.2/1.0/formsession", Order=0)]
    public ProcessActionResponseReturn @return;
    
    public processActionResponse()
    {
    }
    
    public processActionResponse(ProcessActionResponseReturn @return)
    {
        this.@return = @return;
    }
}

//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//public interface FormSessionPortTypeChannel : FormSessionPortType, System.ServiceModel.IClientChannel
//{
//}

//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//public partial class FormSessionPortTypeClient : System.ServiceModel.ClientBase<FormSessionPortType>, FormSessionPortType
//{
    
//    public FormSessionPortTypeClient()
//    {
//    }
    
//    public FormSessionPortTypeClient(string endpointConfigurationName) : 
//            base(endpointConfigurationName)
//    {
//    }
    
//    public FormSessionPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
//            base(endpointConfigurationName, remoteAddress)
//    {
//    }
    
//    public FormSessionPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
//            base(endpointConfigurationName, remoteAddress)
//    {
//    }
    
//    public FormSessionPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
//            base(binding, remoteAddress)
//    {
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    getVersionResponse1 FormSessionPortType.getVersion(getVersionRequest1 request)
//    {
//        return base.Channel.getVersion(request);
//    }
    
//    public GetVersionResponseReturn getVersion(string sessionKey)
//    {
//        getVersionRequest1 inValue = new getVersionRequest1();
//        inValue.sessionKey = sessionKey;
//        getVersionResponse1 retVal = ((FormSessionPortType)(this)).getVersion(inValue);
//        return retVal.@return;
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    System.Threading.Tasks.Task<getVersionResponse1> FormSessionPortType.getVersionAsync(getVersionRequest1 request)
//    {
//        return base.Channel.getVersionAsync(request);
//    }
    
//    public System.Threading.Tasks.Task<getVersionResponse1> getVersionAsync(string sessionKey)
//    {
//        getVersionRequest1 inValue = new getVersionRequest1();
//        inValue.sessionKey = sessionKey;
//        return ((FormSessionPortType)(this)).getVersionAsync(inValue);
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    getDeliveryOptionsResponse1 FormSessionPortType.getDeliveryOptions(getDeliveryOptionsRequest1 request)
//    {
//        return base.Channel.getDeliveryOptions(request);
//    }
    
//    public GetDeliveryOptionsResponseReturn getDeliveryOptions(string sessionKey)
//    {
//        getDeliveryOptionsRequest1 inValue = new getDeliveryOptionsRequest1();
//        inValue.sessionKey = sessionKey;
//        getDeliveryOptionsResponse1 retVal = ((FormSessionPortType)(this)).getDeliveryOptions(inValue);
//        return retVal.@return;
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    System.Threading.Tasks.Task<getDeliveryOptionsResponse1> FormSessionPortType.getDeliveryOptionsAsync(getDeliveryOptionsRequest1 request)
//    {
//        return base.Channel.getDeliveryOptionsAsync(request);
//    }
    
//    public System.Threading.Tasks.Task<getDeliveryOptionsResponse1> getDeliveryOptionsAsync(string sessionKey)
//    {
//        getDeliveryOptionsRequest1 inValue = new getDeliveryOptionsRequest1();
//        inValue.sessionKey = sessionKey;
//        return ((FormSessionPortType)(this)).getDeliveryOptionsAsync(inValue);
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    getDataResponse1 FormSessionPortType.getData(getDataRequest1 request)
//    {
//        return base.Channel.getData(request);
//    }
    
//    public GetDataResponseReturn getData(string sessionKey, FormData dataContainer)
//    {
//        getDataRequest1 inValue = new getDataRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.dataContainer = dataContainer;
//        getDataResponse1 retVal = ((FormSessionPortType)(this)).getData(inValue);
//        return retVal.@return;
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    System.Threading.Tasks.Task<getDataResponse1> FormSessionPortType.getDataAsync(getDataRequest1 request)
//    {
//        return base.Channel.getDataAsync(request);
//    }
    
//    public System.Threading.Tasks.Task<getDataResponse1> getDataAsync(string sessionKey, FormData dataContainer)
//    {
//        getDataRequest1 inValue = new getDataRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.dataContainer = dataContainer;
//        return ((FormSessionPortType)(this)).getDataAsync(inValue);
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    saveContainerResponse1 FormSessionPortType.saveContainer(saveContainerRequest1 request)
//    {
//        return base.Channel.saveContainer(request);
//    }
    
//    public SaveContainerResponseReturn saveContainer(string sessionKey, string resumePath, FormData dataContainer, string view, string viewType, string viewSignature, bool completed, bool continueSession)
//    {
//        saveContainerRequest1 inValue = new saveContainerRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.resumePath = resumePath;
//        inValue.dataContainer = dataContainer;
//        inValue.view = view;
//        inValue.viewType = viewType;
//        inValue.viewSignature = viewSignature;
//        inValue.completed = completed;
//        inValue.continueSession = continueSession;
//        saveContainerResponse1 retVal = ((FormSessionPortType)(this)).saveContainer(inValue);
//        return retVal.@return;
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    System.Threading.Tasks.Task<saveContainerResponse1> FormSessionPortType.saveContainerAsync(saveContainerRequest1 request)
//    {
//        return base.Channel.saveContainerAsync(request);
//    }
    
//    public System.Threading.Tasks.Task<saveContainerResponse1> saveContainerAsync(string sessionKey, string resumePath, FormData dataContainer, string view, string viewType, string viewSignature, bool completed, bool continueSession)
//    {
//        saveContainerRequest1 inValue = new saveContainerRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.resumePath = resumePath;
//        inValue.dataContainer = dataContainer;
//        inValue.view = view;
//        inValue.viewType = viewType;
//        inValue.viewSignature = viewSignature;
//        inValue.completed = completed;
//        inValue.continueSession = continueSession;
//        return ((FormSessionPortType)(this)).saveContainerAsync(inValue);
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    getFormViewResponse1 FormSessionPortType.getFormView(getFormViewRequest1 request)
//    {
//        return base.Channel.getFormView(request);
//    }
    
//    public GetFormViewResponseReturn getFormView(string sessionKey, string formInstanceId)
//    {
//        getFormViewRequest1 inValue = new getFormViewRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.formInstanceId = formInstanceId;
//        getFormViewResponse1 retVal = ((FormSessionPortType)(this)).getFormView(inValue);
//        return retVal.@return;
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    System.Threading.Tasks.Task<getFormViewResponse1> FormSessionPortType.getFormViewAsync(getFormViewRequest1 request)
//    {
//        return base.Channel.getFormViewAsync(request);
//    }
    
//    public System.Threading.Tasks.Task<getFormViewResponse1> getFormViewAsync(string sessionKey, string formInstanceId)
//    {
//        getFormViewRequest1 inValue = new getFormViewRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.formInstanceId = formInstanceId;
//        return ((FormSessionPortType)(this)).getFormViewAsync(inValue);
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    processActionResponse1 FormSessionPortType.processAction(processActionRequest1 request)
//    {
//        return base.Channel.processAction(request);
//    }
    
//    public ProcessActionResponseReturn processAction(string sessionKey, string actionId, System.Xml.XmlElement actionContainer)
//    {
//        processActionRequest1 inValue = new processActionRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.actionId = actionId;
//        inValue.actionContainer = actionContainer;
//        processActionResponse1 retVal = ((FormSessionPortType)(this)).processAction(inValue);
//        return retVal.@return;
//    }
    
//    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
//    System.Threading.Tasks.Task<processActionResponse1> FormSessionPortType.processActionAsync(processActionRequest1 request)
//    {
//        return base.Channel.processActionAsync(request);
//    }
    
//    public System.Threading.Tasks.Task<processActionResponse1> processActionAsync(string sessionKey, string actionId, System.Xml.XmlElement actionContainer)
//    {
//        processActionRequest1 inValue = new processActionRequest1();
//        inValue.sessionKey = sessionKey;
//        inValue.actionId = actionId;
//        inValue.actionContainer = actionContainer;
//        return ((FormSessionPortType)(this)).processActionAsync(inValue);
//    }
//}
