<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Adapters.Hiso\HekCoreApi.Adapters.Hiso.csproj" />
    <ProjectReference Include="..\..\src\Adapters.Karo\HekCoreApi.Adapters.Karo.csproj" />
    <ProjectReference Include="..\..\src\Adapters.Erms\HekCoreApi.Adapters.Erms.csproj" />
  </ItemGroup>

</Project>
